---
- hosts: etcd
  remote_user: root
  gather_facts: false
  tasks:
  - name: 准备证书
    template: src=/data/lin/chap-03/templates/{{ item }} dest=~/TLS/etcd
    with_items:
      - ca-config.json.j2
      - ca-csr.json.j2
      - server-csr.json.j2
- hosts: localhost
  remote_user: root
  gather_facts: false
  tasks:
  - name: 修改证书名称
    shell: |
      mv ~/TLS/etcd/ca-config.json.j2 ~/TLS/etcd/ca-config.json
      mv ~/TLS/etcd/ca-csr.json.j2 ~/TLS/etcd/ca-csr.json
      mv ~/TLS/etcd/server-csr.json.j2 ~/TLS/etcd/server-csr.json
  - name: 生成证书
    shell: |
      cd ~/TLS/etcd
      cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=www server-csr.json | cfssljson -bare server
  - name: 解压文件
    unarchive: src=/tmp/etcd-v3.5.0-linux-amd64.tar.gz dest=/tmp
  #- name: 启动并设置开启启动
  #  systemd: name=etcd state=restarted enabled=yes
  #- name: 检查集群状态
- hosts: etcd
  remote_user: root
  gather_facts: false
  tasks:
  - name: 创建目录
    shell: |
      mkdir /opt/etcd/{{ item }} -p
    with_items:
      - bin
      - cfg
      - ssl
  - name: 创建工作目录
    shell: |
      mkdir -p /opt/etcd/{{ item }}
    with_items:
      - ssl
  - name: 拷贝证书
    copy: src=~/TLS/etcd/{{ item }} dest=/opt/etcd/ssl/{{ item }}
    with_items:
      - ca.pem
      - ca-key.pem
      - server.pem
      - server-key.pem
  - name: 拷贝etcd二进制执行文件
    copy: src=/tmp/etcd-v3.5.0-linux-amd64/{{ item }} dest=/opt/etcd/bin/
    with_items:
      - etcd
      - etcdctl
  - name: 拷贝templates etcd.conf文件
    template: src=/data/lin/chap-03/etcd.conf.j2 dest=/opt/etcd/cfg/etcd.conf
    template: src=/data/lin/chap-03/templates/etcd.conf.j2 dest=/opt/etcd/cfg/etcd.conf
  - name: 拷贝etcd.service文件
    template: src=/data/lin/chap-03/templates/etcd.service.j2 dest=/usr/lib/systemd/system/etcd.service
  - name: 启动并设置开启启动
    systemd: name=etcd state=restarted enabled=yes
